execute pathogen#infect()

"more history
set history=2000

"line numbering
set number
set relativenumber

"tab defaults
set autoindent
set tabstop=4
set shiftwidth=4
set smarttab

"wrap lines
set linebreak

"set display options
set scrolloff=1
set sidescrolloff=5
set display+=lastline

"statusline defaults
set laststatus=2
set ruler

"enable completion for command-line
set wildmenu

"change spellcheck to english
set spelllang=en

"enable sensible splits
set splitbelow
set splitright

"indent by filetype
filetype plugin indent on

"enable syntax highlighting
syntax on

"search defaults
set incsearch
set hlsearch
set ignorecase
set smartcase

"delete comment character when joining commented lines
set formatoptions+=j

"automatically re-read file if changed
set autoread

"use blowfish2 as default encryption method
try
	set cryptmethod=blowfish2
catch
endtry

"change timeout settings
set notimeout
set ttimeout
set ttimeoutlen=0

"clear search highlighting on Leader-c (clear)
nnoremap <Leader>c :nohlsearch<CR>:<BS>

"auto-indent code on cu (clean up)
nnoremap cu gg=G``zz

"map F3 to toggle spellcheck
nnoremap <F3> :set spell! spell?<CR>

"search selection with Leader-s
nnoremap <Leader>s *N
vnoremap <Leader>s y/<C-r>"<CR>``

"navigate wrapped lines with ease
nnoremap <expr> j v:count ? 'j' : 'gj'
nnoremap <expr> k v:count ? 'k' : 'gk'
nnoremap <expr> <Up> v:count ? 'k' : 'gk'
nnoremap <expr> <Down> v:count ? 'j' : 'gj'

"remove trailing spaces with Leader-t
nnoremap <Leader>t :%s/\s\+$//<CR>:nohlsearch<CR>:<BS>

"break undoing sequence when doing deletes
inoremap <C-u> <C-g>u<C-u>
inoremap <C-w> <C-g>u<C-w>
inoremap <BS> <C-g>u<BS>

"make Joins more sensible
nnoremap <expr> J v:count > 1 ? 'JJ' : 'J'

"auto-source *vimrc on save
augroup vimrc_source
	autocmd!
	autocmd BufWritePost *vimrc source %
augroup END

"make Y behave like D and C
nnoremap Y y$

"add theming
set background=dark

"smarter tabline
let g:airline#extensions#tabline#enabled = 1

"make : faster
nnoremap <Enter> :
vnoremap <Enter> :

"use C-[hjkl] for window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"remap missing C-l
nnoremap <F5> <C-l>

"make buffer navigation faster
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>
